language: ruby
cache: bundler
rvm:
  - 2.2.3

gemfile:
  - Gemfile

before_script:
  - mysql -e 'create database activerecord_import_test;'
  - psql -c 'create database activerecord_import_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - cp test/travis/database.yml test/database.yml
# https://github.com/discourse/discourse/blob/master/.travis.yml
  - export RUBY_GC_MALLOC_LIMIT=50000000

script:
  - test/travis/build.sh

sudo: false
